repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Update to the latest version available
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Update to the latest version available
    hooks:
    -   id: flake8
