name: CI
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: netpicker/crt
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Run yaml tests
        run: collect-jobs --co -p comfy.automate --no-summary --rootdir $PWD/jobs $PWD/jobs
