name: CI
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: netpicker/crt
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Run Job Collection
        run: PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 collect-jobs --co -p comfy.automate --no-summary --rootdir $PWD/jobs $PWD/jobs
