name: CI
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: netpicker/api
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Run yaml tests
        env: 
          JWT_SECRET: xxx
        run: collect-rules -p comfy.plugin --co -vvv --rootdir $PWD $PWD
